In [1]:
import pandas as pd
import numpy as np

import random

In [2]:
price = pd.read_csv("../data/forex_price_data.csv")

price["DateTime"] = pd.to_datetime(price["DateTime"])

price.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6

In [3]:
price["Return"] = price["Close"].pct_change()

price = price.dropna().copy()

In [4]:
price["State"] = np.where(
    price["Return"] > 0,
    1,
    0
)

price[["Close","Return","State"]].head()

     Close    Return  State
1  1.08028 -0.000241      0
2  1.08054  0.000241      1
3  1.08088  0.000315      1
4  1.08030 -0.000537      0
5  1.07998 -0.000296      0

In [5]:
actions = {
    0: "BUY",
    1: "SELL",
    2: "HOLD"
}

print(actions)

{0: 'BUY', 1: 'SELL', 2: 'HOLD'}

In [6]:
actions = {
    0: "BUY",
    1: "SELL",
    2: "HOLD"
}

print(actions)

{0: 'BUY', 1: 'SELL', 2: 'HOLD'}

In [9]:
# Reward Function

def get_reward(entry_price, exit_price, action):

    # BUY
    if action == 0:
        return exit_price - entry_price

    # SELL
    elif action == 1:
        return entry_price - exit_price

    # HOLD
    else:
        return 0

In [10]:
print("BUY Reward :",
      get_reward(100,105,0))

print("SELL Reward :",
      get_reward(100,95,1))

print("HOLD Reward :",
      get_reward(100,105,2))

BUY Reward : 5
SELL Reward : 5
HOLD Reward : 0

In [2]:
import sys
import os

# Add the project root to Python path
project_root = os.path.abspath("..")
if project_root not in sys.path:
    sys.path.append(project_root)

import pandas as pd

from src.feature_engineering import create_features

price = pd.read_csv("../data/forex_price_data.csv")

price = create_features(price)

price.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,MA_5,...,High_Low_Range,Return,RSI,MACD,MACD_Signal,MACD_Histogram,BB_Upper,BB_Middle,BB_Lower,Target
33,2023-01-02 09:00:00,1,EUR/USD,1.07481,1.07502,1.07455,1.07495,4396,1.3,1.074880,...,0.00047,0.000484,36.741694,-0.001439,-0.001303,-0.000137,1.081662,1.077130,1.072597,0
34,2023-01-02 10:00:00,1,EUR/USD,1.07407,1.07493,1.07407,1.07447,3250,1.5,1.074832,...,0.00086,-0.000447,34.782970,-0.001431,-0.001328,-0.000102,1.081132,1.076808,1.072484,1
35,2023-01-02 11:00:00,1,EUR/USD,1.07523,1.07523,1.07445,1.07489,3058,1.7,1.074692,...,0.00078,0.000391,37.902444,-0.001374,-0.001337,-0.000036,1.080610,1.076534,1.072459,1
36,2023-01-02 12:00:00,1,EUR/USD,1.07575,1.07662,1.07531,1.07605,3856,1.8,1.074958,...,0.00131,0.001079,45.636715,-0.001221,-0.001314,0.000093,1.079969,1.076313,1.072658,1
37,2023-01-02 13:00:00,1,EUR/USD,1.07707,1.07707,1.07613,1.07660,2991,1.6,1.075392,...,0.00094,0.000511,48.887311,-0.001044,-0.001260,0.000216,1.079665,1.076199,1.072734,1

In [3]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from src.feature_engineering import create_features
from src.rl_environment import ForexEnvironment
from src.q_learning import QLearningAgent

import pandas as pd

price = pd.read_csv("../data/forex_price_data.csv")

price = create_features(price)

In [4]:
from src.rl_environment import ForexEnvironment
from src.q_learning import QLearningAgent

In [5]:
# Create Environment

env = ForexEnvironment(price)

print("Environment Created Successfully")

Environment Created Successfully

In [6]:
actions = ["BUY", "SELL", "HOLD"]

agent = QLearningAgent(actions)

print("Q-Learning Agent Created")

Q-Learning Agent Created

In [2]:
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd

from src.feature_engineering import create_features
from src.rl_environment import ForexEnvironment
from src.q_learning import QLearningAgent

In [3]:
price = pd.read_csv("../data/forex_price_data.csv")

price = create_features(price)

In [4]:
env = ForexEnvironment(price)

print("Environment Created Successfully")

Environment Created Successfully

In [5]:
actions = ["BUY", "SELL", "HOLD"]

agent = QLearningAgent(actions)

print("Agent Created Successfully")

Agent Created Successfully

In [7]:
print(type(env))

<class 'src.rl_environment.ForexEnvironment'>

In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd

from src.feature_engineering import create_features
from src.rl_environment import ForexEnvironment
from src.q_learning import QLearningAgent

In [2]:
price = pd.read_csv("../data/forex_price_data.csv")

price = create_features(price)

In [3]:
print(price.columns.tolist())

['DateTime', 'PairID', 'PairName', 'Open', 'High', 'Low', 'Close', 'Volume', 'Spread', 'MA_5', 'MA_20', 'Price_Change', 'High_Low_Range', 'Return', 'RSI', 'MACD', 'MACD_Signal', 'MACD_Histogram', 'BB_Upper', 'BB_Middle', 'BB_Lower', 'Target', 'RSI_State', 'MACD_State', 'Trend_State']

In [4]:
env = ForexEnvironment(price)

actions = ["BUY", "SELL", "HOLD"]

agent = QLearningAgent(actions)

state = env.reset()

print(state)

(np.int64(1), np.int64(0), np.int64(0))

In [5]:
episodes = 100

for episode in range(episodes):

    state = env.reset()

    done = False

    while not done:

        # Choose Action
        action = agent.choose_action(state)

        # Execute Action
        next_state, reward, done = env.step(action)

        # Learn from Experience
        agent.learn(
            state,
            action,
            reward,
            next_state
        )

        # Move to Next State
        state = next_state

print("Training Completed!")

Training Completed!

In [6]:
print("Total Learned States:", len(agent.q_table))

# Show first 5 learned states
count = 0

for state, values in agent.q_table.items():
    print(f"State: {state} -> {values}")
    count += 1

    if count == 5:
        break

Total Learned States: 6
State: (np.int64(1), np.int64(0), np.int64(0)) -> [np.float64(0.0007473956741567558), np.float64(0.0007957612070239866), np.float64(0.0009108891667273648)]
State: (np.int64(1), np.int64(1), np.int64(0)) -> [np.float64(0.0015871809124152255), np.float64(0.0010004256972563793), np.float64(0.001139784061322352)]
State: (np.int64(1), np.int64(1), np.int64(1)) -> [np.float64(0.0007661476029745977), np.float64(0.0006963190460045358), np.float64(0.001126723023239923)]
State: (np.int64(1), np.int64(0), np.int64(1)) -> [np.float64(0.0012355476201386616), np.float64(0.0002516231555512714), np.float64(0.0009833702374156394)]
State: (np.int64(0), np.int64(0), np.int64(0)) -> [np.float64(0.0005461750152111473), np.float64(0.000697884606018496), np.float64(0.0008378620527878882)]

In [7]:
action_names = ["BUY", "SELL", "HOLD"]

policy = {}

for state, q_values in agent.q_table.items():

    best_action = q_values.index(max(q_values))

    policy[state] = action_names[best_action]

print("Learned Trading Policy:\n")

count = 0

for state, action in policy.items():

    print(state, "->", action)

    count += 1

    if count == 10:
        break

Learned Trading Policy:

(np.int64(1), np.int64(0), np.int64(0)) -> HOLD
(np.int64(1), np.int64(1), np.int64(0)) -> BUY
(np.int64(1), np.int64(1), np.int64(1)) -> HOLD
(np.int64(1), np.int64(0), np.int64(1)) -> BUY
(np.int64(0), np.int64(0), np.int64(0)) -> HOLD
(np.int64(2), np.int64(1), np.int64(1)) -> SELL